#!/bin/bash
python main_test_associative.py -N
python main_test_associative.py -F
python main_test_associative.py -C
python main_test_associative.py -E 1
python main_test_associative.py -E 2
python main_test_associative.py -E 3
python main_test_associative.py -E 4
python main_test_associative.py -E 5
python main_test_associative.py -E 6
python main_test_associative.py -E 7
python main_test_associative.py -E 8
python main_test_associative.py -E 9
python main_test_associative.py -E 10
python main_test_associative.py -E 11
python main_test_associative.py -E 12
