#!/bin/bash
#python main_test_associative.py -n
python main_test_associative.py -f
python main_test_associative.py -c
python main_test_associative.py -e 1
python main_test_associative.py -e 2
python main_test_associative.py -e 3
python main_test_associative.py -e 4
python main_test_associative.py -e 5
python main_test_associative.py -e 6
python main_test_associative.py -e 7
python main_test_associative.py -e 8
python main_test_associative.py -e 9
python main_test_associative.py -e 10
python main_test_associative.py -e 11
python main_test_associative.py -e 12
